@extends('blogVgs_components.createView')

@section('createView')
    <div class="body-right">

        <div class="tab_panel container">
            <div class="title">Panel form fields</div>
            <div class="tabs-top">
                <div class="tab">
                    <div class="open" style="display: flex;">
                        <img srcset="/open.png 2x" alt="">
                        Open
                    </div>
                    <div class="unlisted" style="display: flex;">
                        <img srcset="/circle_half.png 2x" alt="">
                        Unlisted
                    </div>
                    <div class="settings" style="display: flex;">
                        <img srcset="/cog.png 2x" alt="">
                        Settings
                    </div>
                </div>

                <div class="arrows">
                    <i class="fa-solid fa-angle-left"></i>
                    <i class="fa-solid fa-angle-right"></i>
                </div>
            </div>

            <div class="row options">
                <!-- Tab links -->
                <div class="tab">
                    <button class="tablinks chose" onclick="openCity(event, 'London')" style="display: flex;"><img
                            srcset="Vector.png 2x" alt="">
                        CONTENT</button>
                    <button class="tablinks" onclick="openCity(event, 'Paris')" style="display: flex;"><img
                            srcset="cog.png 2x" alt="">
                        SETTINGS</button>
                </div>

                <!-- Tab content -->
                <div id="London" class="row tabcontent d-flex" style="margin: 0 auto;">
                    <form action="{{ asset('') }}blogVgs" method="POST" enctype="multipart/form-data"
                        class="row" id="form">
                        {{ csrf_field() }}
                        <input type="hidden" name="validate">
                        <!-- noi dung content -->
                        <div class="col-12 col-md-6 left">
                            <div class="files mt-3">

                                <label for="profile_image" class="item-title mb-2">Image</label>
                                <input
                                    style="    background: white;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 6px; margin-bottom: 20px"
                                    type="file" name="profile_image">


                                {{-- <div class="item-title d-flex w-100"
                                    style="justify-content: space-between; align-items: center; margin-bottom: 10px;">
                                    <div>Image</div>

                                    <div>
                                        <div class="upload-img d-flex" style="align-items: center;">
                                            <div id="yourBtn" name="profile_image" onclick="getFile()"><i
                                                    style="font-size: 15px; margin-right:10px"
                                                    class="fa-solid fa-circle-plus"></i></div>
                                            <button class="upload">Upload</button>
                                        </div>
                                        <div style='height: 0px;width: 0px; overflow:hidden;'><input id="upfile" type="file"
                                                value="upload" onchange="sub(this)" /></div> --}}

                                {{-- </div>

                            </div>
                            <div class=" row files-img">
                                <div class="p-0" style="padding-right: 5px!important;">
                                    <div class="card" style="">
                                        <img srcset="Rectangle11.png 2x" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <p class="m-0">Bird-reynolds.jpg</p>
                                            <i style="cursor: pointer;" class="fa-solid fa-circle-minus"></i>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}
                                @if ($errors->has('profile_image'))
                                    <span class="text-danger">{{ $errors->first('profile_image') }}</span>
                                @endif
                            </div>

                            <div class="title-headline d-flex mb-5" style="">
                                <div class=""
                                    style="margin-right: 10px; font-weight: 400;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            font-size: 24px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            line-height: 28px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* Blue/600 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #4271AE;">
                                    01
                                </div>
                                <div
                                    style="font-weight: 400;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            font-size: 24px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            line-height: 28px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* gray/900 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #111111;  -webkit-line-clamp: 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -webkit-box-orient: vertical;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            overflow: hidden;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: -webkit-box;">
                                    I’m a headline, use me to provide some structure
                                </div>
                            </div>
                            <div class="info-headline"
                                style="height: 130px; border-bottom: 1px solid #CCCCCC; margin-bottom: 30px;">
                                <div
                                    style="font-weight: 500;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            font-size: 18px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            line-height: 21px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* identical to box height */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* gray/900 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #111111; margin-bottom: 10px; ">
                                    Info
                                </div>
                                <div class="headline">
                                    <p>Info fields are great to provide some context for editors</p>
                                </div>
                            </div>

                            <div class="description mb-3">
                                <div class="item-title mb-3">
                                    Description
                                </div>
                                <textarea name="description" id="description" cols="" rows=""
                                    style="width: 100%; height: 100px; padding: 10px"></textarea>
                                <small class="client"></small>
                                <span class="client"></span>
                                @if ($errors->has('description'))
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                @endif

                            </div>

                        </div>

                        <div class="col-12 col-md-6 right">

                            <div class="range mb-3 mt-3">
                                <div class="item-title mb-2">Range</div>
                                <div class="range-budget">
                                    <label for="customRange1" class="form-label m-0 pr-1"
                                        style="padding-left:7px; padding-right: 7px;">Budget</label>
                                    <input id="myinput" type="range" min="0" value="25" max="200" style="">
                                    <img style="height: 18px; padding: 0; width: 55px; padding-left: 7px;"
                                        srcset="after.png 2x" alt="">
                                </div>
                            </div>

                            <div class="select-input mb-4" style="width:100%">
                                <div class="item-title mb-2">Select</div>
                                <select id="options" name="options" class="form-select"
                                    style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: 1px solid #CCCCCC;"
                                    aria-label="Default select example">
                                    <option value="kinh nghiệm du lịch" selected>Kinh nghiệm du lịch</option>
                                    <option value="trải nghiệm ẩm thực">Trải nghiệm ẩm thực</option>
                                    <option value="vé máy bay">Vé máy bay</option>
                                    <option value="tin tức và sự kiện">Tin tức & sự kiện</option>
                                    <option value="bài viết nổi bật">Bài viết nổi bật</option>
                                </select>
                            </div>

                            <div class="text-field">
                                <div class="item-title d-flex" style="justify-content: start; text-align: center;">
                                    <p>Tiêu đề</p>
                                    <p
                                        style="display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                align-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin-top: 5px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin-left: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: #999999;">
                                        *
                                    </p>
                                </div>

                                <div class="text-field_input email">
                                    <input id="title" name="title" type="text" placeholder="Text input">
                                    <small class="client"></small>
                                    <span class="client"></span>
                                    @if ($errors->has('title'))
                                        <span class="text-danger">{{ $errors->first('title') }}</span>
                                    @endif
                                </div>

                                <div class="help mt-2 mb-5">Help text</div>
                            </div>


                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="item-title mb-3">Bài viết đầu trang</div>
                                    <div class="toggle-item">
                                        <label class="switch" style="margin-right: 10px;">
                                            <input type="checkbox" id="head" name="head">
                                            <span class="slider round"></span>
                                        </label>
                                        <div>Có</div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div>
                                <div class="item-title mb-3">Nội dung</div>
                                <div class="ckediter" id="ckediter">
                                    <textarea name="content" id="content"></textarea>
                                    <small class="client small-editor"></small>
                                    <span class="client span-editor"></span>
                                    @if ($errors->has('content'))
                                        <span class="text-danger text-content">{{ $errors->first('content') }}</span>
                                    @endif
                                    <span class="form-message_ckediter"></span>
                                </div>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-success"
                            style="width: 113px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin: 0 auto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin-top: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin-bottom: 50px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    justify-content: center;">Submit</button>
                    </form>

                </div>

                <div id="Paris" class="tabcontent">
                    <!-- noi dung setting -->
                </div>
            </div>
            <script>
                var form = document.querySelector('#form');
                var title = document.querySelector('#title');
                var description = document.querySelector('#description');

                function showError(input, message) {
                    let small = input.parentElement.querySelector('small');
                    input.parentElement.classList.add('error');
                    small.innerText = message;
                }

                function showSuccess(input) {
                    let small = input.parentElement.querySelector('small');
                    input.parentElement.classList.remove('error');
                    small.innerText = '';
                }

                function checkValidate(listInput) {
                    let check = true;
                    listInput.value = listInput.value.trim();
                    if (listInput.value == "") {
                        check = false;
                        showError(listInput, "Không được bỏ trống...");
                    } else {
                        check = checkLength(listInput, 3, 20);
                    }
                    return check;
                }

                function checkEditor(editor) {
                    let check = true;
                    let value = editor.getData().split("&nbsp;")
                    let string = "";
                    for (let i = 0; i < value.length; i++) {
                        if (value[i] != " ") {
                            string += value[i];
                        }
                    }
                    console.log(string);
                    if (string == "") {
                        check = false;
                        let small = document.querySelector('.small-editor');
                        //input.parentElement.classList.add('error');
                        small.innerText = "Không được bỏ trống...";
                    } else {
                        let small = document.querySelector('.small-editor');
                        // input.parentElement.classList.remove('error');
                        small.innerText = '';
                    }
                    return check;
                }

                function checkLength(input, min, max) {
                    let check = true;
                    input.value = input.value.trim();
                    if (input.value.length < min) {
                        check = false
                        showError(input, `Phải có ít nhất ${min} kí tự...`);

                    } else if (input.value.length > max) {
                        check = false
                        showError(input, `Không được quá ${max} kí tự...`)

                    } else {
                        showSuccess(input)
                    }
                    return check;
                }

                //console.log(checkValidate([description]));

                form.addEventListener('submit', function(e) {

                    let check2 = checkEditor(editor);
                    let check1 = checkValidate(description);
                    if (!checkValidate(title) || !check1 || !check2) {
                        e.preventDefault();

                    }
                });



                // form.addEventListener('submit', function(e) {

                //     let check = checkValidate([title]);
                //     if (!check) {
                //         e.preventDefault();
                //     }
                // })
            </script>
        </div>
    </div>
@endsection
